### PR TITLE
Fixes for contraflow lanes & fwd/bkwd bike infra parsing

### LINKED ISSUE #70: Respect in oneway:bicycle tags
It doesn't seem to be allowing bikes to go on oneway streets with a contraflow bikelane if the bike track is not mapped seperately. Haw hill is an example
conzelman
hawk-hill-oneway

### LINKED ISSUE #119: Mishandling of cycleway:left:oneway=-1?
We're avoiding going northbound on Scott between Oak and Fell, specifically the part at the very north end of the block where motor vehicles are not allowed to travel south:

image

It's clearly avoiding this little part:

image

Southbound works:

image

The way at the very north end is tagged

```
oneway=yes
oneway:bicycle=no
cycleway:right=lane
cycleway:left=lane
cycleway:left:oneway=-1
```
These tags seem correct. The bug might be that we treat `cycleway:left:oneway=-1` and `cycleway:right:oneway=-1` as equivalent to `oneway:bicycle=-1`. (See `isBackwardOneway()`.) The latter means that bicycles can only travel opposite the OSM way direction on the entire road.

### PR DESCRIPTION
**Pull request by graue**
1. On `master`, the `OSMCyclewayParser` parses `cycleway` properties for exposing to the frontend, which ultimately renders them on the map (green "lane", dashed green "shared lane", dark green "track", etc.). In doing so, it makes assumptions that are often not valid, such as that cycleways on the drive side always go forward and opposite the drive side always go backward (contradicted by two-way cycle tracks), and that one-way streets (for cars) can only have one cycleway value (contradicted by contraflow lanes). The first commit in this PR fixes these situations.
2. On `master`, `BikeCommonFlagEncoder` assumes that if a street is one-way for cars, it's also one-way for bikes, despite the fact that `oneway=yes` + `oneway:bicycle=no` is a common OSM tagging practice for a street which allows contraflow bicycle traffic (seen on Lyell St north of Alemany in SF). `BikeCommonFlagEncoder` also assumes that if a street contains a bike lane that is explicitly marked as a one-way bike lane (which is the default!), the whole street is one-way. The second commit in this PR fixes these situations, so the router can correctly use contraflow bike lanes (such as the aforesaid Lyell St).
3. On `master`, when assigning penalties based on street conditions, instead of reusing the forward and backward cycleway values computed by `OSMCyclewayParser`, `BikeCommonFlagEncoder` does its own parsing of `cycleway` tags (which also contains errors relating to one-ways, etc.). The third commit in this PR makes the flag encoder use the already parsed forward and backward cycleway values, so penalty assignment also benefits from the corrected logic in the first commit.

I've verified this correctly handles (not an exhaustive list):
1. Battery Street from Market to Vallejo, two-way cycle track, both forward and contraflow directions (previously broken)
2. Scott Street just south of Fell Street, one-way north but two-way for bikes, both directions (previously broken)
3. Lyell Street, both directions (previously broken)
4. Fell Street, one-way cycle track on one-way street (still works)
5. Indiana Street forward and contraflow bike lanes, 26th St to Cesar Chavez (previously broken)

Fixes #70 

Fixes #119

### CODE REVIEW

File: core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java [hunk 1]
```diff
@@ -586,11 +571,20 @@ void collect(IntsRef edgeFlags, ReaderWay way, double wayTypeSpeed,
...
-
-        if (isOneway(way) || roundaboutEnc.getBool(false, edgeFlags)) {
-            boolean isBackward = isBackwardOneway(way);
-            accessEnc.setBool(isBackward, edgeFlags, true);
+        boolean isRoundabout = roundaboutEnc.getBool(false, edgeFlags);
+        boolean isOnewayForCars = isRoundabout || way.hasTag("oneway", oneways);
+        boolean isBackwardOnewayForCars = way.hasTag("oneway", "-1");
+        boolean hasBikeExceptionToOneway = (
+            way.hasTag("oneway:bicycle", "no")
+            || way.hasTag("cycleway", oppositeLanes)
```
Comment (abhumbla) [inline core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java:579]: what does `oppositeLanes` mean here? maybe it's worth a comment explaining every exception?

File: core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java [hunk 2]
```diff
@@ -13,81 +13,122 @@
...
+        Cycleway cycleway = Cycleway.find(readerWay.getTag("cycleway"));
+
+        // Default forward and backward to the "cycleway" value until we find a more
+        // specific value.
+        Cycleway cyclewayForward = cycleway, cyclewayBackward = cycleway;
+
+        // If we find opposite_* tags, normalize them, and treat that as the final word
+        // (discounting any contradictory left/right tags which would be a tagging error).
+        if (oppositeLanes.containsKey(cycleway)) {
+            cyclewayForward = Cycleway.SHARED_LANE;
```
Comment (abhumbla) [inline core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java:69]: why do we set `cyclewayForward` to `Cycleway.SHARED_LANE`. shouldn't it keep its old value of `Cycleway.find(readerWay.getTag("cycleway"))`

File: core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java [hunk 3]
```diff
@@ -13,81 +13,122 @@
...
+            cyclewayBackward = oppositeLanes.get(cycleway);
+        } else {
+            // Driving side is needed to compute default directionality of cycleway:left/right.
+            // See defaults described in wiki:
+            // https://wiki.openstreetmap.org/wiki/Key:cycleway:right:oneway
+            DrivingSide drivingSide = DrivingSide.find(readerWay.getTag("driving_side"));
```
Comment (abhumbla) [inline core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java:75]: shouldn't this be after the country rule? in the case that the country as a whole drives on the left but this way for some reason drives on the right? could happen in a diverging diamond interchange

https://www.wikiwand.com/en/Diverging_diamond_interchange

**Review by abhumbla — APPROVED** [review]
looks good to me, minor comments

File: core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java (hunk 2 above)
Comment (graue) [reply core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java:69]: Because it doesn't make sense to say, "In the forward direction, the bike infra consists of a bike lane in the opposite direction." So I normalize it like the comment says.

See the documentation for the "opposite" values, starting with why they're discouraged: https://wiki.openstreetmap.org/wiki/Key:cycleway#Problems_with_opposite*_values

Comment (abhumbla) [reply core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java:69]: that's fine, just wondering why `Cycleway.SHARED_LANE` is the default. could lead to incorrect behavior? unless this value is ignored in which case maybe `Cycleway.MISSING` is a better value? maybe im misunderstanding

Comment (graue) [reply core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java:69]: That's my interpretation of what the value is intended to be in the forward direction when the opposite values are used. Do you have a different interpretation of the tag docs, and on what basis?

Comment (abhumbla) [reply core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java:69]: ah i see, i was misunderstanding `cycleway=opposite*`. objection retracted. for my information, how does the local `oppositeLanes` variable work? what info does it hold?

Comment (abhumbla) [reply core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java:69]: should this be `oppositeLanes.get(cycleway)` instead so that `opposite_share_busway` can become `Cycleway.SHARE_BUSWAY` etc? or is the intention to flatten everything to `Cycleway.SHARED_LANE`

Comment (graue) [reply core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java:69]: `opposite_share_busway` has [no documentation and 99 uses](https://wiki.openstreetmap.org/wiki/Key:cycleway=opposite_share_busway) in the entire world and has been deprecated for years. We are way in the weeds even having this conversation. But my interpretation is that no, "You can bike on this otherwise one-way road by sharing the contraflow bus lane" does not imply "Also, there's a bus lane in the forward direction that you should also use."

Comment (abhumbla) [reply core/src/main/java/com/graphhopper/routing/util/parsers/OSMCyclewayParser.java:69]: im pretty unclear on what `cycleway=opposite_track` etc means for the forward direction. i guess the options are make forwards and backwards the same, or pick a default value for forwards. my vote for a default value is still `Cycleway.MISSING`, because we don't have any information on what the forward direction
